### ISSUE TITLE
Где можно взять готовую DLL?

### ISSUE THREAD

**Issue by Carw** [zamgi/lingvo--PosTagger-ru-dnn#1]
Добрый день!

Спасибо за интересный проект и открытый код. Есть ли возможность реализовать решение в виде DLL для дальнейшего подключения к другим системам?

**Comment by zamgi** [comment]
добрый,

там же есть и DLL и их подключение консоли/сервису(?).

**Comment by Carw** [comment]
@zamgi Прошу прощения за неточность, я подразумевал уже скомпилированную DLL, чтобы не устанавливать все необходимое окружение для разработки.

**Comment by zamgi** [comment]
ну, в репозиторий выкладывать дльльки неправильно, могу прислать на почту.
вообще странно - если будет собранная дльлька, что бы ещё подключить к проекту всё равно студия нужна, или я чего-то  не понимаю? и как следствие - что подразумевается под "все необходимое окружение для разработки", окромя студии?

**Comment by Carw** [comment]
@zamgi возможно, в качестве релиза было бы полезно выкладывать и сами готовые библиотеки.
Я хочу попробовать использовать DLL для работы в NodeJS. В том числе на Mac. Пока не знаю к чему приведет этот эксперимент, но очень хочется попробовать.  Буду благодарен, если получится выслать готовую DLL мне на почту - carw.master+dll@gmail.com
PS: Я с удивлением обнаружил, что для Mac тоже есть VS. Похоже, что все же получится поэкспериментировать и с самим кодом.

**Comment by zamgi** [comment]
Это письмо создано автоматически сервером Mail.ru, отвечать на него не нужно.

К сожалению, Ваше письмо не может быть доставлено одному или нескольким получателям:

  [carw.master+dll@gmail.com](https://e.mail.ru/compose?To=carw.master%2bdll@gmail.com)
    SMTP error from remote mail server after end of data:
    host gmail-smtp-in.l.google.com [173.194.222.26]:
    552-5.7.0 This message was blocked because its content presents a potential
    552-5.7.0 security issue. Please visit
    552-5.7.0 https://support.google.com/mail/?p=BlockedMessage to review our
    552 5.7.0 message content and attachment content guidelines. x6-20020a0565123f8600b0046bc312b117si14390701lfa.416 - gsmtp

Рекомендуем Вам проверить корректность указания адресов получателей.

**Comment by Carw** [comment]
К сожалению, не все поддерживают стандарт. Можно отправить просто на carw.master@gmail.com

**Comment by zamgi** [comment]
Это письмо создано автоматически сервером Mail.ru, отвечать на него не нужно.

К сожалению, Ваше письмо не может быть доставлено одному или нескольким получателям:

  [carw.master@gmail.com](https://e.mail.ru/compose?To=carw.master@gmail.com)
    SMTP error from remote mail server after end of data:
    host gmail-smtp-in.l.google.com [142.251.1.26]:
    552-5.7.0 This message was blocked because its content presents a potential
    552-5.7.0 security issue. Please visit
    552-5.7.0 https://support.google.com/mail/?p=BlockedMessage to review our
    552 5.7.0 message content and attachment content guidelines. b14-20020a2ebc0e000000b0024f10bdb806si1828901ljf.411 - gsmtp

Рекомендуем Вам проверить корректность указания адресов получателей.

**Comment by Carw** [comment]
Вот это новость (
Прошу прощения, мне уже становится неловко, что возникает столько трудностей. Поставлю студию и попробую скомпилировать самостоятельно. Спасибо огромное за ваш труд и поддержку )

**Comment by zamgi** [comment]
как вариант, можно почту использовать другую/не гугловую.

**Comment by Carw** [comment]
Спасибо огромное, я поставил студию и скомпилировал все. Оказалось, что это крайне просто, в сравнении с тем , как это работало лет 10 назад. И нам Mac все отлично скомпилировалось. Буду экспериментировать )
